### ISSUE TITLE
Update the node js

### ISSUE THREAD

**Issue by KarateTD** [KarateTD/thebestdarngirls#59]
update node js from 10 to 14

**Comment by sankalp123-w** [comment]
What do you want , is it to update node version on your machine ?

**Comment by KarateTD** [comment]
Its an update for Lambda and the underlying technology.  AWS Lambda no longer sports NodeJS 10, I have to update to NodeJS14.  I can do it.  I just needed to map out all the changes, so I don’t forget anything.


Tiffany Gray
***@***.***
**********
On the web
1. My Blog:  https://thatdarngirlmovie.reviews/
2. Alexa Skill: https://amzn.to/34PUfeX
3. Facebook: https://www.facebook.com/thebestdarngirls/
4. Twitter: https://twitter.com/TheBestDarnGirl

**Comment by sankalp123-w** [comment]
Step 1 - Get NVM (Node Version Manger)
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
If you're curious about the installation command read the source code
... its been reviewed by several node.js security experts

Step 2 - Install the version of node.js you need
Once you've got NVM you can install a specific version of Node.js using the nvm command:

nvm install v14.17.0
Note: you may need to close & re-open your terminal window for nvm command to be available.

You should expect to see something like this in your terminal:

Now using node v14.17.0
Step 3 - Enjoy the rest of your day!

After that you have to go to your project directory and run 
npm install 
It will install and update all dependency according to node version -14 
And now you can run your app with your start script

**Comment by KarateTD** [comment]
Update complete.  Will keep an eye on https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html#linux-runtimes to update CodeBuild from node: 12 to node: 14

**Comment by KarateTD** [comment]
#BadDadRehab: The Next Session review is up.  Shortlink:  https://wp.me/p65txm-aPM/#BadDadRehab Permalink: https://thatdarngirlmovie.reviews/2021/06/27/doomsdaymom-thestrangershebroughthome-and-more-tv-reviews/#BadDadRehab

TV One

4 stars 

Tiffany Gray
***@***.***
**********
On the web
1. My Blog:  https://thatdarngirlmovie.reviews/
2. Alexa Skill: https://amzn.to/34PUfeX
3. Facebook: https://www.facebook.com/thebestdarngirls/
4. Twitter: https://twitter.com/TheBestDarnGirl
